### ISSUE TITLE
yeh kya hai??

### ISSUE THREAD

**Issue by PranjalAsthana** [hrshb05/CollabCanvas#1]
kya karta hai yeh??

**Comment by hrshb05** [comment]
Hey Pranjal, this is a tool that is gonna help every designer as well as a developer for efficiently performing their daily tasks, let me quickly take you through this tool.

- This is a collaborative tool that has real-time collaboration features like multi-cursors, chat, and reactions for interactive feedback between the designers and even the developers.
- As well as it has advanced design tools such as shape creation, image uploads, freeform drawing, and undo/redo functionality, along with keyboard shortcuts for a better user experience.
- It also has Customization options for efficient canvas management, including actions like delete, scale, move, and export.
- And last but not the least an attempt to resolve the never-ending battle between a developer and a designer 😅.

I hope you would have got your query resolved.
